// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwx0Se3zm09xGdH2KnrwD2jtiL-MvMN4',
    appId: '1:1009964498010:web:REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: '1009964498010',
    projectId: 'scancall-f8c81',
    authDomain: 'scancall-f8c81.firebaseapp.com',
    storageBucket: 'scancall-f8c81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwx0Se3zm09xGdH2KnrwD2jtiL-MvMN4',
    appId: '1:1009964498010:android:b1f3ad1a92d75e19616c63',
    messagingSenderId: '1009964498010',
    projectId: 'scancall-f8c81',
    storageBucket: 'scancall-f8c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwx0Se3zm09xGdH2KnrwD2jtiL-MvMN4',
    appId: '1:1009964498010:ios:REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '1009964498010',
    projectId: 'scancall-f8c81',
    storageBucket: 'scancall-f8c81.firebasestorage.app',
    iosBundleId: 'co.protonestiot.scancallMobileApp',
  );
}
